Make `getElapsedTime` test more reliable
Before this change, I ran into this test failure:

??????????????????????????????????????? Failed Tests 1 ????????????????????????????????????????

 FAIL  src/fsm.test.ts > getElapsedTime > should work after state change
AssertionError: expected 999 to be greater than or equal to 1000
 ? src/fsm.test.ts:137:36
    135|     state.change('starting')
    136|     await setTimeout(1000)
    137|     expect(state.getElapsedTime()).toBeGreaterThanOrEqual(1000)
       |                                    ^
    138|     expect(state.getElapsedTime()).toBeLessThan(2000)
    139|   })

?????????????????????????????????????????????????????????????????????????????????????????[1/1]?

The issue is that `state.change()` happened to take 1 ms before it updated
`startTime`, so elapsed time ended up being 999 ms instead of 1000+ ms.